### ISSUE TITLE
How to enable device scanning?

### ISSUE THREAD

**Issue by Hoeze** [nullp0tr/bluew#8]
Hi, how can I enable device scanning with this package?

**Comment by nullp0tr** [comment]
Scanning is started automatically by calling bluew.devices(), you need to upgrade to 0.4.5 though, since when changing from get_devices() to devices() the start_scanning() call was left out by mistake. Is there a reason why you might want scanning to be a separate API call? or is it enough that it starts when you call bluew.devices()?

**Comment by Hoeze** [comment]
Well, I just could not find any devices with 0.4.4.
A separate call would be cool nevertheless, as I could choose to scan all the time and get the devices at any time point I choose, independent of an enabled device scanning option.

Maybe something like this:

```
def devices(enable_scanning=True):
	if enable_scanning:
		set_discovery_state(True)
	devices = get_devices()
	if enable_scanning:
		set_discovery_state(False)
	return devices

def set_discovery_state()
	[...]
```

**Comment by nullp0tr** [comment]
I think adding a scanning option might clutter the API, specially since devices() keeps scanning enabled. But regarding your other point about constantly querying for new devices, I was thinking of adding a couple of listener functions, that observe devices/adapters that are added/removed, and notify the user. I'm gonna close this issue for now, but if you're interested in the listeners please open a new issue:)

**Comment by Hoeze** [comment]
Well, listeners would be indeed a nice feature.
I'm currently writing a bluetooth device manager which should allow to configure adapters and add / remove devices; having a listener api would be helpful to this.

Regarding the enable / disable option: This might be implemented in a (lower-level) device API.
I'm not sure, if simply keeping scanning enabled is a good option, as some user might want to disable it in order to save energy or due to privacy concerns.
Having the option if needed is always better than relying on sys.call() :grin:
